# -*- coding: utf-8 -*-
"""HipotesaLatihan-RifaaRaihan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zgOjGmJkTrhpE7SOIniHySGmjxwLzMzT

# Latihan 

Misalkan kamu adalah data scientist di gojek. Kamu ingin mengetahui apakah kemacetan mempengaruhi tingkat kepuasan pelanngan.

Kamu diminta unutk membandingkna nilai "bintang" dari customer setalah dia order

macet = [2, 3, 5, 4, 4, 2, 2, 2]
tidak macet = [ 4 , 3, 5, 4 , 4, 5,5]

Tugas
1. Buat hipotesa
2. Lakukan uji asumis normaltias
3. Jika datanya normal, lakukan uji paramterik
4. jika datanya tidak nrmal lakukan uji non parametrik
5. kesimpulan?
"""

# import library

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np
from scipy import stats

"""#Mendefenisikan nillai menjadi Array"""

macet       = np.array  ([2, 3, 5, 4, 4, 2, 2, 2])
tidakMacet = np.array  ([ 4 , 3, 5, 4 , 4, 5, 5])

"""Uji Normalitas

Ho =  Data berdistribusi normal

Ha = data tidak berdistribusi normal
"""

# Dengan Histogram saat keadaan macet
sns.distplot(macet)

#Dengan Histogram saat kedaan tidak macet
sns.distplot(tidakMacet)

"""Berdasarkan data diatas. Data tersebut berada di tengah yang menandakan data tersebut normal."""

#UJI KOLMOGORV-SMIRNOV -> MENENTUKAN APAKAH DATA INI BERDISTRIBUSI NORMAL ATAU TIDAK

z_score_macet = stats.zscore(macet)
z_score_tidakMacet = stats.zscore(tidakMacet)

print("Stats of data macet ", stats.kstest(z_score_macet, "norm"))
print("Stats of data tidakMacet ", stats.kstest(z_score_tidakMacet, "norm"))

"""Jika p-value > 0.05, maka Ho Diterima, data berdistribusi normal

jika maka sebaliknyaJika p-value > 0.05, maka Ho Diterima, data berdistribusi normal

jika maka sebaliknya

#Paired Sample - Test (Paramterik)
Ho = Tidak ada perbedaan yang signifikan

ha = Ada perbedaan
"""

len(tidakMacet)

len(macet)

"""#Kesimpulan

## Dapat Disimpulkan bahwa keadaan macet dapat mempengaruhi tingkat kepuasaan pelanggan atau pengguna dalam menggunakan aplikasi gojek
"""